### ISSUE TITLE
Please make note about pyproj more prominent 

### ISSUE THREAD

**Issue by bodysurfinyon** [fitnr/stateplane#1]
So, state plane looks great. This is my first experience with github, so, I did notice that this is just a wrapper for pyproj
...
    import pyproj
ImportError: No module named pyproj

Now I installed pyproj, but, shapely is missing. I reran 'sudo python setup.py install' for stateplane but I'm missing geos

GEOS is a whole rendering engine. Is that really needed?

**Comment by fitnr** [comment]
Shapely and pyproj are both listed in `setup.py`, so should be installed automatically by pip, or upon `python setup.py install`. I've added a note explaining installation, in case that wasn't clear.

[GEOS](http://trac.osgeo.org/geos/) provides geometry functions for Shapely. `Stateplane` uses these for matching a point with the area that a projection is valid in. I would be happy to know of a lighter way of getting these functions, and will happily accept a pull request.

**Comment by bodysurfinyon** [comment]
Thank you for getting back to me. You got me to install pyproj, and since I am just hacking locally, that is all I need.

import pyproj

def convert(x, y):
    state_plane = pyproj.Proj(init='EPSG:2249', preserve_units=True)
    wgs = pyproj.Proj(proj='latlong', datum='WGS84', ellps='WGS84')
    lng, lat = pyproj.transform(state_plane, wgs, x, y)
    return lat, lng

print convert( 692266,2975458)
