### ISSUE TITLE
Installation (Python 2.7 Ubuntu)

### ISSUE THREAD

**Issue by geneorama** [fitnr/stateplane#2]
I tried installing this in Windows, but had issues with pip (probably because of a clash between python versions, mingw issues, or sun spots).

So, I tried it in Ubuntu.  

`sudo pip install pyproj` completed without error, but `import stateplane` didn't work within python.

``` python
Python 2.7.6 (default, Jun 22 2015, 18:00:18)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import stateplane
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named stateplane
```

So, I cloned this project and ran setup.py, per the README.  The installation completed, but now I get this error:

``` python
Python 2.7.6 (default, Jun 22 2015, 18:00:18)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import stateplane
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "stateplane/__init__.py", line 11, in <module>
    from . import stateplane
  File "stateplane/stateplane.py", line 12, in <module>
    with fiona.open('/', vfs='zip://' + os.path.join(os.path.dirname(__file__), 'data/stateplane.zip')) as src:
  File "build/bdist.linux-i686/egg/fiona/__init__.py", line 163, in open
IOError: no such archive file: 'stateplane/data/stateplane.zip'
```

Any idea what I'm doing wrong?

Thanks, 

Gene

**Comment by geneorama** [comment]
Actually, installing with `pip3`  and using python3 works.  So, maybe close?

**Comment by SpongebobSquamirez** [comment]
Do you know how I can install it with Anaconda? Anaconda can get pyproj (but pycharm doesn't detect stateplane, only pyproj), but I get an error when I try to do pip install stateplane from the Anaconda/Scripts directory (using Windows 7). The error is actually inconsistent too.
![screenshot 2016-10-16 03 46 54](https://cloud.githubusercontent.com/assets/11866755/19416044/826cd06c-9353-11e6-8053-2d5a76442817.png)

**Comment by fitnr** [comment]
@weirdalsuperfan It looks like you're missing the GEOS and GDAL libraries, which are required.

**Comment by daniellivingston** [comment]
I get this same error, even though I have GEOS and GDAL built:

    Python 2.7.10 (default, Feb  7 2017, 00:08:15)
    [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import gdal
    >>> import geos
    >>> import stateplane
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "stateplane/__init__.py", line 11, in <module>
        from . import stateplane
    File "stateplane/stateplane.py", line 12, in <module>
        with fiona.open('/', vfs='zip://' + os.path.join(os.path.dirname(__file__), 'data/stateplane.zip')) as src:
    File "/Library/Python/2.7/site-packages/fiona/__init__.py", line 160, in open
        raise IOError("no such archive file: %r" % archive)
    IOError: no such archive file: 'stateplane/data/stateplane.zip'

**Comment by fitnr** [comment]
@daniellivingston please open a new issue and include the method you used to install the library
