### ISSUE TITLE
Cannot build from wheel or pip

### ISSUE THREAD

**Issue by daniellivingston** [fitnr/stateplane#4]
When trying to build stateplane from [this wheel](https://pypi.python.org/pypi/stateplane/0.1.1), the following error is generated:

    $ wget https://pypi.python.org/packages/06/ca/b16709b04a0c0fab29e9a3eef2a0ba43073fb3e8b1771ba51e4b04c9003c/stateplane-0.1.1-py2-none-any.whl
    $ sudo python -m wheel install stateplane-0.1.1-py2-none-any.whl
    $ python
    Python 2.7.10 (default, Feb  7 2017, 00:08:15)
    [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import gdal
    >>> import geos
    >>> import stateplane
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "stateplane/__init__.py", line 11, in <module>
        from . import stateplane
    File "stateplane/stateplane.py", line 12, in <module>
        with fiona.open('/', vfs='zip://' + os.path.join(os.path.dirname(__file__), 'data/stateplane.zip')) as src:
    File "/Library/Python/2.7/site-packages/fiona/__init__.py", line 160, in open
        raise IOError("no such archive file: %r" % archive)
    IOError: no such archive file: 'stateplane/data/stateplane.zip'

When trying to build from `pip`,

    $ sudo -H pip install stateplane
    $ python
    Python 2.7.10 (default, Feb  7 2017, 00:08:15)
    [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import stateplane
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "stateplane.py", line 7, in <module>
        from . import data
    ValueError: Attempted relative import in non-package

Fortunately, building from the repo works:

    $ git clone https://github.com/fitnr/stateplane.git stateplane
    Cloning into 'stateplane'...
    remote: Counting objects: 177, done.
    remote: Total 177 (delta 0), reused 0 (delta 0), pack-reused 177
    Receiving objects: 100% (177/177), 1.32 MiB | 1.84 MiB/s, done.
    Resolving deltas: 100% (101/101), done.
    $ cd stateplane
    $ python setup.py install --user
    $ python
    Python 2.7.10 (default, Feb  7 2017, 00:08:15)
    [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import stateplane
    >>> stateplane.identify(-73.2, 43.2)
    u'32145'

**Comment by fitnr** [comment]
unable to reproduce.
