### ISSUE TITLE
quantMode in STAR

### ISSUE THREAD

**Issue by novicele** [fitnr/stateplane#5]
Hello,
I am absolutely new to programming and I am trying to learn to use STAR to align and get gene counts for RNA seq files. I have been successful in running the basic protocol to get a .bamaligned output but when I try adding the quantMode I get this error. Any suggestions would be great. 

./code/STAR-2.5.4a/bin/Linux_x86_64/STAR --runThreadN 10 --genomeDir ./genomeDir/ --sjdbGTFfile Homo_sapiens.GRCh38.79.gtf --sjdbOverhang 100 --readFilesIn  ENCFF001RFH.fastq.gz ENCFF001RFG.fastq.gz --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate  –-quantMode GeneCounts –-outFileNamePrefix “resultoutput”

this is the error I get 
EXITING because of fatal input ERROR: unknown value for the word 3 of outSAMtype: –-quantMode

**Comment by fitnr** [comment]
I think you meant this for a different repo.
