### ISSUE TITLE
Lat/Long and State Plane Conversion

### ISSUE THREAD

**Issue by Avetis-Av** [fitnr/stateplane#8]
I am working on a similar project, but using C#. I have been looking through the code trying to understand how the conversions work, but I am having trouble with sample inputs for the program. Would you mind explaining how the "point", --statefp, --countyfp, --output-type, inputs work? Can you also explain the computation behind the conversions?

P.S. After `import stateplane` in __main__.py, I get the error that "'stateplane' had no attribute 'identify'"

**Comment by fitnr** [comment]
I'm sorry, this isn't the right venue for explaining how to install a Python package. Try `pip install stateplane`.

Generally speaking, the package uses a reference mapping of counties to state plane systems.

**Comment by Avetis-Av** [comment]
Is it possible to use that package for use in c#?
